### ISSUE TITLE
How to run benchmark-driver? and discussion about the various modes

### ISSUE THREAD

**Issue by eregon** [benchmark-driver/benchmark-driver#67]
I looked at the README and I'm still quite confused.

Suppose I have `bench.rb` with:
```ruby
require 'benchmark_driver'

Benchmark.driver do |x|
  x.prelude <<~RUBY
    require 'active_support/all'
    array = []
  RUBY

  x.report 'blank?', %{ array.blank? }
  x.report 'empty?', %{ array.empty? }
end
```

How I am supposed to run it? The README doesn't say anything.

* `ruby bench.rb` seems to work (it creates 4 subprocesses). But then can I pass any option to this gem?
* `benchmark-driver bench_dev.rb` does something and creates 1 subprocess but it seems completely wrong and to measure the time to execute the whole subprocess, reporting as a single entry instead of the `blank?` and `empty?` jobs inside:
```
$ benchmark-driver bench.rb 
Calculating -------------------------------------
               bench      0.072 i/s -       1.000 times in 13.872230s (13.87s/i)
benchmark-driver bench.rb  13.83s user 0.17s system 99% cpu 14.083 total
```

I think essentially there are 3+ modes to run benchmarks in `benchmark-driver`?
* Ruby files which `require 'benchmark_driver'`
* Ruby files which do not `require 'benchmark_driver'` and then it seems just to measure the wall script execution time? That's always extremely imprecise, I would strongly recommend against this mode, or at least it should be explicit like `benchmark-driver --measure-process-wall-time script.rb`.
* YAML files, which seems to be somehow the main way? The huge drawback for me there is there is no syntax highlighting in YAML and it's very easy to make typos and not measure what's intended.

**Comment by k0kubun** [comment]
> ruby bench.rb seems to work (it creates 4 subprocesses). But then can I pass any option to this gem?

You're supposed to do it in `prelude`.

> benchmark-driver bench_dev.rb does something and creates 1 subprocess but it seems completely wrong

The interface of benchmark-driver taking Ruby script is relatively new and I'm sorry but it's not documented in https://github.com/benchmark-driver/benchmark-driver#structured-yaml-input which explains the CLI.

It's basically for a single-run slow script like `*.rb` files in https://github.com/ruby/ruby/tree/master/benchmark. Users of benchmark-driver are usually not supposed to use this interface. Think `benchmark-driver` CLI as YAML runner basically.

<hr>

> I think essentially there are 3+ modes to run benchmarks in benchmark-driver?

Right.

> Ruby files which do not require 'benchmark_driver' and then it seems just to measure the wall script execution time? That's always extremely imprecise, I would strongly recommend against this mode, or at least it should be explicit like benchmark-driver --measure-process-wall-time script.rb.

I have never recommended it either. You don't need to strongly recommend against this mode to me. I'll add a short description about it in README later.

It's just for making it easier to maintain some of ruby/ruby benchmark scripts, because some committers complained that these scripts should remain as Ruby scripts.

> YAML files, which seems to be somehow the main way? 

It tends to be maintained a little more often. However, its feature set should be ideally the same with `Ruby files which require 'benchmark_driver'`. Therefore it depends on user. You're not forced to use YAML interface. Pick your preference. YAML interface was proposed by ko1. As I thought similar things as you, I added Ruby interface to it too.

Note that one of the major goals of benchmark-driver was to replace legacy ruby/ruby/benchmark/driver.rb. We wanted to take measured code as String instead of a block so that benchmark-driver can dynamically generate a script to measure it without an overhead to call blocks. If everything is not a Ruby block but String, we can naturally express the same thing in YAML. 

> The huge drawback for me there is there is no syntax highlighting in YAML and it's very easy to make typos and not measure what's intended.

Don't use YAML format then. I'd say editors should support or have plugin in YAML string for mixed syntax highlight just like markdown's code block, by reading YAML comment or something.

As we provide an option not to use it, users can decide which to use, and benchmark-driver has nothing to do on what happens on editors.

**Comment by eregon** [comment]
Thanks for the quick reply.

> You're supposed to do it in `prelude`.

How does that work, is it documented?
Can I set `--run-duration` for instance? What about `--rbenv`?

> The interface of benchmark-driver taking Ruby script is relatively new and I'm sorry but it's not documented in https://github.com/benchmark-driver/benchmark-driver#structured-yaml-input which explains the CLI.

I think my main issue here is from the README I couldn't be sure how I'm supposed to run a Ruby file which requires benchmark-driver.

> It's basically for a single-run slow script like `*.rb` files in https://github.com/ruby/ruby/tree/master/benchmark. Users of benchmark-driver are usually not supposed to use this interface. Think `benchmark-driver` CLI as YAML runner basically.

Right I thought it was that.
I think https://github.com/ruby/ruby/tree/master/benchmark should use "Ruby files which require benchmark-driver".
I don't think it's useful to measure startup in each of these `.rb` file and the added error because of that. It would be much more useful for regression testing to measure what differs in those benchmarks.
@ko1 @k0kubun  Thoughts?

> I have never recommended it either. You don't need to strongly recommend against this mode to me. I'll add a short description about it in README later.

I think it should not be the default and require some flag, because it's typically a very imprecise way to measure (or even be removed if there is no more usage for it).
Instead, I think the default for `benchmark-driver bench.rb` should be the same as `ruby bench.rb` but with easy access to all benchmark-driver options, for instance to run against multiple rubies.

And for the case that the script does contain `require 'benchmark_driver'` (my first example) I think it should error out because then it's an invalid usage, isn't it?

> It's just for making it easier to maintain some of ruby/ruby benchmark scripts, because some committers complained that these scripts should remain as Ruby scripts.

I agree, syntax highlighting and IDE integration is the main issue with YAML files.

> > YAML files, which seems to be somehow the main way?
> 
> It tends to be maintained a little more often. However, its feature set should be ideally the same with `Ruby files which require 'benchmark_driver'`.

I think the main difference right now is options and ability to run with multiple Ruby interpreters.

> Note that one of the major goals of benchmark-driver was to replace legacy ruby/ruby/benchmark/driver.rb. We wanted to take measured code as String instead of a block so that benchmark-driver can dynamically generate a script to measure it without an overhead to call blocks. If everything is not a Ruby block but String, we can naturally express the same thing in YAML.

I thought it was that. As said above, how about using `Benchmark.driver do |x|` in those? It would lead to better measurements.

> Don't use YAML format then. I'd say editors should support or have plugin in YAML string for mixed syntax highlight just like markdown's code block, by reading YAML comment or something.

But does any editor currently support that?
And what magic comment would it make realize it's Ruby code?
I think this is major drawback for YAML benchmarks until such support is available in most editors and it's easy to enable it.

**Comment by k0kubun** [comment]
> How does that work, is it documented?
> Can I set --run-duration for instance? What about --rbenv?

About the prelude, aren't you using it in your script with `x.prelude`? Can't your option for the gem be explained in the Ruby script writtein in `x.prelude`?

`--run-duration` is a good point. It was forgotten... It's to be fixed.
`--rbenv` is just `x.rbenv`.

> I think my main issue here is from the README I couldn't be sure how I'm supposed to run a Ruby file which requires benchmark-driver.

understood, I agree :+1: Filed https://github.com/benchmark-driver/benchmark-driver/issues/69 as an individual issue separated from this discussion.

> I think https://github.com/ruby/ruby/tree/master/benchmark should use "Ruby files which require benchmark-driver".

I'm also specifically _against_ that. By unifying files under ruby/ruby/benchmark to be runnable as an argument of benchmark-driver CLI, we can flexibly do many things over multiple Ruby scripts, for example `--filter` over all files, comparing multiple benchmark files instead of just inside one Ruby script requiring "benchmark-driver".

<hr>

I think I already spent too much time for writing this and the discussion does not seem to progress efficiently here. I'd like to discuss it in person when we meet next time, and summarize the conclusions here instead. WDYT?

**Comment by eregon** [comment]
> > I think https://github.com/ruby/ruby/tree/master/benchmark should use "Ruby files which require benchmark-driver".
> 
> I'm also specifically _against_ that. By unifying files under ruby/ruby/benchmark to be runnable as an argument of benchmark-driver CLI, we can flexibly do many things over multiple Ruby scripts, for example `--filter` over all files, comparing multiple benchmark files instead of just inside one Ruby script requiring "benchmark-driver".

I'm not sure what you mean.
If each such `.rb` file does `require 'benchmark-driver'` and then `Benchmark.driver do |x| ...`, all files could still be executed by `benchmark-driver file.rb|yml`, assuming `benchmark-driver file.rb` doesn't time the whole script but is the same as `ruby file.rb`, which I think is anyway a good thing.
Something less nice would be that the entire class definitions would have to be in `x.prelude` (a consequence of this gem's design), but at least that can be syntax-highlighted easily in most editors.

`--filter` could load all *.yml and all *.rb files to filter, no?
---

> I think I already spent too much time for writing this and the discussion does not seem to progress efficiently here. I'd like to discuss it in person when we meet next time, and summarize the conclusions here instead. WDYT?

I'm not sure when we'll meet next time in person, though (if RUbyKaigi it's still in 3 months).
How about having a video or audio call, or otherwise discuss on Slack?

**Comment by k0kubun** [comment]
> I'm not sure when we'll meet next time in person, though (if RubyKaigi it's still in 3 months).
> How about having a video or audio call, or otherwise discuss on Slack?

I'll be relatively busy in January and February for personal reasons and therefore I'll be able to allocate time for this amount of discussion and implementation/review from March. At that time I'm okay to do the discussion in whatever format.

**Comment by eregon** [comment]
OK, I'll add myself a reminder in March to find some time to discuss this.

**Comment by eregon** [comment]
I had a call with @k0kubun, here is my summary of the call:
* I'd like to simplify to 2 modes:
  * Existing `benchmark-driver bench.yml`
  *  `benchmark-driver bench.rb` where `bench,rb` uses DSL like in the README.
    I'd also warn or deprecate `ruby bench.rb` where `bench,rb` uses DSL, because that seems confusing (I'd expect everything runs inside that process but it's not the case, and it's inconvenient to pass e.g. `--executables/--rbenv`, better have a consistent entry point since benchmark-driver always uses subprocesses).

That would mean removing the 3rd mode which is currently `benchmark-driver bench.rb` where `bench,rb` *does not* use the DSL. That needs discussion which @ko1.

We could then rewrite .rb benchmarks in MRI like [app_answer.rb](https://github.com/ruby/ruby/blob/master/benchmark/app_answer.rb) to use the DSL (pro: would allow syntax highlighting), or to use `.yml` (pro: all MRI benchmarks would use YAML).
That would also avoid measuring startup in all those `.rb` benchmarks which is not very interesting (I think it's better to have a single benchmark measuring startup explicitly, and other benchmarks don't measure startup)

**Comment by eregon** [comment]
Regarding the issue of syntax highlighting for .yml files, one workaround could be to have some option for `benchmark-driver` to generate a Ruby file from the .yml file. That could either be prelude + report, or use the `Benchmark.driver` DSL which would then be a way to convert `.yml` to `.rb`, with the nice bonus of editing the `.rb` would allow to run the modified benchmark.

Regarding the reason that benchmark-driver uses Strings as inputs it's to avoid block overhead, which e.g., would be unfair to MRI without JIT and add significant overhead for benchmarking MRI.

**Comment by k0kubun** [comment]
> I'd also warn or deprecate `ruby bench.rb` where `bench.rb` uses DSL, because that seems confusing (I'd expect everything runs inside that process but it's not the case, and it's inconvenient to pass e.g. `--executables/--rbenv`, better have a consistent entry point since benchmark-driver always uses subprocesses).

I admit it's confusing to allow both `ruby bench.rb` and `becnhmark-driver bench.rb`, but I'm still reluctant to deprecate that since the DSL interface was originally created for users who used to run benchmarks with `ruby xxx.rb` using stdlib benchmark or benchmark-ips.

Some thoughts about this problem:

> that seems confusing (I'd expect everything runs inside that process but it's not the case

This is understandable, but if that's confusing, when we're just reading benchmark definitions and not aware of how it's used, we'd be confused anyway even if everybody uses it with `benchmark-driver`. I think we may be able to have interface which is less confusing for that point.

> it's inconvenient to pass e.g. --executables/--rbenv, better have a consistent entry point since benchmark-driver always uses subprocesses)

`ruby bench.rb [benchmark-driver's options]` could also be an option, just like we do `ruby test.rb -n test_name`. A downside is that we need to have `require` for `.rb` files.

<hr>

I'm not insisting with the above options because they have trade-offs. I think there are major two directions _in a world where we successfully deprecated the current `benchmark-driver bench.rb` interface_:

* Single mode (top-level DSL) for everything
  * Ruby DSL for `benchmark-driver bench.rb`: Design a brand-new top-level DSL, which should be simple and very similar to the current YAML syntax.
  * Ruby DSL for `ruby bench.rb`: Deprecate. By doing so we can eliminate `require` in benchmark scripts.
  * YAML for `benchmark-driver bench.yml`: This could be deprecated (and there will be only one mode!) if the top-level DSL is good enough to achieve YAML's original motivation.
* Maintain the backward compatibility
  * Ruby DSL for `benchmark-driver bench.rb`: Just implement it on the current DSL.
  * Ruby DSL for `ruby bench.rb`: Keep the current interface, and you'd need to write `require` in whatever bench.rb. We may consider taking options like `ruby bench.rb [options]`.
  * YAML for `benchmark-driver bench.yaml`: Nothing is changed.

**Comment by eregon** [comment]
@ko1 Specifically I'm proposing to remove the 3rd mode which is `benchmark-driver bench.rb` where `bench.rb` *does not* use the DSL, because I find that confusing and inconsistent with other modes for benchmark-driver. In such a mode, timing is not done precisely but is the entire script wall time including startup. That means measurements are imprecise due to these benchmarks measuring startup instead of focusing on the actual workload.

I think the only files using that mode are in ruby/ruby `benchmark` directory, such as [app_answer.rb](https://github.com/ruby/ruby/blob/master/benchmark/app_answer.rb) and I propose for them use the `Benchmark.driver` DSL instead, so they would still be Ruby files, but would provide more precise measurements, and, e.g., give the possibility to run them with warmup if desired.

**Comment by ko1** [comment]
I have no strong opinion about it.
Maybe the 3rd option is special form of YAML file, which body is `load 'xxx.rb'` and it is no confusion about it. If it is confusing for somebody, introduce xxx.yaml explicitly for xxx.rb is nice idea for me.

**Comment by k0kubun** [comment]
This discussion seems outdated. Closing. At this point, I'm reluctant to change the benchmarking modes for compatibility reasons.

**Comment by eregon** [comment]
I think due to this confusion, it's basically very hard for non-CRuby devs to use benchmark-driver and understand how it works/the various modes.
But this may not matter, I think most Rubyists are better off with the simpler benchmark-ips.

**Comment by k0kubun** [comment]
Yup, I use benchmark-ips too and I don't feel like this tool need to cover both use cases. It's unnecessarily too complicated to support comparing different Ruby binaries when measuring a single Ruby is enough, which is what non-CRuby devs do most of the time.

**Comment by eregon** [comment]
That's a good point, a `benchmark-ips`-like warmup + mode (Ruby API) together with the builtin ability to compare multiple Rubies would be quite useful.
#68 seems the main blocker for that.
But probably the benchmark-driver approach of generating a file and not being able to pass any data in easily is not really compatible with a Ruby API taking blocks (https://github.com/benchmark-driver/benchmark-driver/pull/74#issuecomment-623115791 was an attempt to reconcile that but it's rather tricky).
